server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:proddb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: false

logging:
  level:
    root: WARN
    com.example.demo: INFO
  file:
    name: logs/application.log

app:
  environment: 生产环境
  debug: false

custom:
  upload-path: /data/upload/prod
  max-file-size: 2MB
